s,t = map(int, input().strip().split(' '))
a,b = map(int, input().strip().split(' '))
m,n = map(int, input().strip().split(' '))
apple = list(map(int, input().strip().split(' ')))
orange = list(map(int, input().strip().split(' ')))
s1 = sum([1 for f in apple if (f+a) in range(s,t+1)])
s2 = sum([1 for f in orange if (f+b) in range(s,t+1)])
print (s1)
print (s2)
